### PR TITLE
GNU Octave release (2024-06-01)

### PR DESCRIPTION
**Pull request by mmuetzel**
@siko1056: Does this change look good to you?
Is pushing changes to this repository enough to update the website?  Or are there additional steps that need to be triggered?

### CODE REVIEW

**Review by siko1056 — APPROVED** [review]
Thank you for making all the changes for the release.

You can always safely deploy the page here in GitHub anytime.  It is just a preview.  When the page here on GitHub looks fine, we have to manually pull and build the page on octave.org (jwe's Digital Ocean) server.

I am happy to share this knowledge which anyone interested.  Most likely you need an account on jwe's Digital Ocean server.

**Comment by siko1056** [comment]
@mmuetzel Does the page look like you expect it?  Then I can publish it on octave.org anytime this weekend.

https://gnu-octave.github.io/

EDIT: My last change on the main branch was not necessary, I got fooled by being sent to octave.org from the test page :sweat:

**Comment by mmuetzel** [comment]
> @mmuetzel Does the page look like you expect it?  Then I can publish it on octave.org anytime this weekend.
> 
> https://gnu-octave.github.io/
> 
> EDIT: My last change on the main branch was not necessary, I got fooled by being sent to octave.org from the test page :sweat: 

Thanks! 🙏 

It looks good to me. 👍

**Comment by siko1056** [comment]
Thanks for the confirmation.  The changes are now live.  I updated the README file with the instructions what to do on the Digital Ocean server.

https://github.com/gnu-octave/gnu-octave.github.io?tab=readme-ov-file#gnu-octave-website-development

**Pull request merged**
